# Generated by Django 4.1.7 on 2023-03-31 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control_No_ForRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses_ForRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Fee_ForRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_fee', models.FloatField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_ForRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Grade_ForRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Result_ForRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone_Number', models.IntegerField()),
                ('Profile_Pic', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d')),
                ('Gender', models.CharField(max_length=10)),
                ('Added_On', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update_On', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.IntegerField(blank=True, null=True)),
                ('SGPI', models.FloatField(max_length=5)),
                ('Subject', models.CharField(max_length=200)),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.exam_forref')),
                ('Exam_Fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.exam_fee_forref')),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.grade_forref')),
                ('Result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.result_forref')),
                ('control_No', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.control_no_forref')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.courses_forref')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Middle_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Father_Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=30)),
                ('PRN', models.IntegerField(blank=True)),
                ('Roll_No', models.IntegerField()),
                ('Control_Number', models.IntegerField()),
                ('Profile_Pic', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d')),
                ('Fee_pdf', models.FileField(blank=True, null=True, upload_to='Fee_Pdf/%Y/%m/%d')),
                ('is_fee_paid', models.BooleanField(default=False)),
                ('Phone_Number', models.IntegerField()),
                ('Address', models.CharField(blank=True, max_length=500)),
                ('Course', models.CharField(max_length=30)),
                ('Class', models.CharField(max_length=10)),
                ('Semester', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Added_On', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update_On', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
