# Generated by Django 4.1.7 on 2023-04-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultisOut_ForRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Result_Out', models.BooleanField(default=False, verbose_name='Check is Result is ready to Publish !!!')),
            ],
            options={
                'verbose_name_plural': 'ResultisOutDataBase',
            },
        ),
        migrations.AlterModelOptions(
            name='control_no_forref',
            options={'verbose_name_plural': 'ControlNoDataBase'},
        ),
        migrations.AlterModelOptions(
            name='courses_forref',
            options={'verbose_name_plural': 'CourseDataBase'},
        ),
        migrations.AlterModelOptions(
            name='exam_fee_forref',
            options={'verbose_name_plural': 'ATKTExamFeeDataBase'},
        ),
        migrations.AlterModelOptions(
            name='exam_forref',
            options={'verbose_name_plural': 'ATKTExamDataBase'},
        ),
        migrations.AlterModelOptions(
            name='grade_forref',
            options={'verbose_name_plural': 'GradeDataBase'},
        ),
        migrations.AlterModelOptions(
            name='result_forref',
            options={'verbose_name_plural': 'ResultDataBase'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student_Information'},
        ),
        migrations.AlterModelOptions(
            name='student_result',
            options={'verbose_name_plural': 'Student_Result_Information'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Teacher_Informatioon'},
        ),
    ]
