# Generated by Django 4.1.7 on 2023-04-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_resultisout_forref_alter_control_no_forref_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultisout_forref',
            name='Remark',
            field=models.BooleanField(default=False, verbose_name='Select Yes if All result is set'),
        ),
    ]
