# Generated by Django 4.1.7 on 2023-04-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_resultisout_forref_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultisout_forref',
            name='Remark',
        ),
    ]
